[gcp_service_account]
type = "service_account"
project_id = "second-conquest-454415-i5"
private_key_id = "9c3e0f9ae51fd26928dd7d6350e749ec669252d4"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTyUY/K0udSIj0
jmGB4fInXVN67MP3glNFGv+VyckHcP/cF6Hzj/ZFhGCbiuP4PP15gMOp/fLjh0u0
vptCcuYF54N5c/Xs0G9gRsrY+PZEt0K8eopWFau9WMdgPLL1/YQZr/YEcSbKliJm
zzNmbxdDqflZ37UYcZGgxyJlXhWEaw7KFFhYaw6IG/IaS6jt8/PM04gmHDJ6De1+
5CY76c+0VfBs7vC53m6gtViAZavrXAwwRaDZhrQeo5O4cZeWgStRz3etGvP6wWe3
Xu1yAKgYO22dqk0HPMB3KMsomIizcQN5d6puO8jSBkrAuncB7pBrHdEKsHvKPmlL
dI/OakcVAgMBAAECggEAF6F3KZg6nSeZRHRYk+Xyn4rNxEMD0Kulf+n1x7BWsnJc
0iF+7A7No08UenaCXlHr1HFWI7MWtWWEwHueFkl8uf7tkBEsyQouyzbK7m/FBsDN
/PrNUbKkUYHE6UuMil8JrNYR5Mf9VJBw8TjAWvcdSOr/zBPmgH43ihF+GIJpczdM
3iqZLtqozqlUxrY3s+8fM0LMiENRfbJMCuUYeIhWFhCV3jEXF+l324sZW1f+Uoc2
vwJ6r0YjaaTDjMKLZ6J0rcHJVprswf1vQlyeUIOuFHP1uMxLIyn1Ji/WNngvSwMS
ck2xmgMcXMw2+KvLTItaEkKaQz6AjS8QoGx4JsbppwKBgQDqQyaUq6uF+mgVHQsl
Iu3WI4fQzXhQpsAEe9swW7Z4Ds+JCPZn6snKXrUuWf7BRqnXFd6ews2ggzBHC6x1
lOD32Fjz02SaHM4j87jXtOxvMbYlH1+3cdOeO1a6uAwj3iszYQAmI6psM1rCXCVd
k2HSq4XHoVXa0cXRQD/MfeZqEwKBgQDncDWbbyN+oocf3yCbhgc2xDwgi3XWRaZQ
4CBrvr04KOxwSl0RqEEF5XCHL+35RrJoavd20N6d4ZD64GeDo5ANGP+EhPcEQa7Q
dAavUQH/PJryhVPYqVg/pz6qC+KKbOZCLN83JIqForF+CMxYCGO5gipRtaVYHH2k
TBLWR9AvNwKBgQDNP4ByCecCP98pgITfSLcxQ3gfjaa4oyDhzNLCj9hTYEadPekG
K0QZttjvf5IhLRRpipO+bddTpx2JYcT8UDC7diaZmsEt9cb24Pc2pyHwWpHH/LEU
PPq4TC0080RPuLwJDBfhUqZinqwKVkm2rwaqWfWgbs6WJe035R8Av949WQKBgQCw
BuJfBFrk2E0Z6qVsZLZb60koH6pSfMsQvEcsa/iTHF0o0waShXxfNbEuwT+o1yKe
1Ky/TAHl50hT6BYTQ3Yu4BKIAnG2ZRbHKVhkQ6LXNItNZibtpW+fil7ZCw0U59sB
/gsQb9SD68g/6gUx97+RuvThDN1jdNgC/HFfVWN8ZQKBgBq5gQmzki6yZg3Cuk+C
+zojuGrsQOP5sk6AYk96JXZWdJbUbWc7bLpBiI+vUQWDJpf0zM5HQHZNLE32ZISj
T/qZ1j8nl7hQ141L4YMaO58YkG6WMwm3N/irVwaercfgyJf2WrjeWA8Ho7cWB4dp
6PAyiB7dcKuCDcp8ox3rFcAU
-----END PRIVATE KEY-----
"""
client_email = "ntxhh-789@second-conquest-454415-i5.iam.gserviceaccount.com"
client_id = "110384582248184772647"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/.../cert.pem"

SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/1lG4NN4kdk-bcKqWh0fYYRorMSCIypWqsByJvfwO8KgY/edit"
TEMPLATE_DOC_ID = "1rqRTFLG3D0v4Sz7mnJ9iREOxyl1YWLexXyJVMJa_Ezk"
